### ISSUE TITLE
OWM transition

### ISSUE THREAD

**Issue by oknyshuk** [pauleeeeee/open-weather-graph#2]
Can you please switch to OWM API? DarkSky is dead, and I love this watchface!

**Comment by pauleeeeee** [comment]
Hi, you make a good point. OWM would make this face more available to others. But, correct me if I am wrong, OWM does not offer 7 day hourly forecast. Because of this limitation the face would need to adapt to the change in graph scale. 7 days of 24 hour weather data is 144 data points which happens to be the pixel width of the Pebble screen which is very convenient from a programming perspective. Also the OWM format is different than DarkSky. These two challenges prevent me from adapting OWM because I have limited time for this project. You are welcome to contribute if you are able.

**Comment by oknyshuk** [comment]
Okay, if OWM isn't a variant, I think you should try Pirate Weather: docs.pirateweather.net/en/latest/API 
Pirate Weather follows the DarkSky syntax and is free as far as I know

**Comment by pauleeeeee** [comment]
Thanks for the suggestion - that is an awesome API and it appears to be a drop-in replacement for DarkSky. I went ahead and added support for Pirate Weather in the latest release. Please try it out and let me know if there any problems.
